# Generated by Django 2.1.4 on 2019-01-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_passinger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passinger',
            new_name='Passenger',
        ),
    ]
